content_dir: "content"
output_dir: "synced_files"
formats:
  - markdown
  - python
  - clean_python
  - html
html_options:
  template: "basic"
  include_code: true
  include_outputs: true
# Uncomment and modify if you want to process specific notebooks only
# specific_notebooks:
#   - "Week_2_8/WS_2_8_dirty_water.ipynb"
#   - "Week_2_8/WS_2_8_solution.ipynb"