name: mude-week-8
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pyvinecopulib
  - numpy
  - scipy
  - pandas
  - matplotlib
  - sympy           # PA 1.8
  - seaborn         # avoid pip, for bivariate
  - scikit-learn    # avoid pip, for bivariate
  - threadpoolctl   # avoid pip, for scikit-learn
  - joblib          # avoid pip, for scikit-learn
  - jupyter
  - ipykernel
  - pip
  - pip:
    - bivariate